mod args;
mod port_lookup;
mod processes;

use args::Args;
use clap::Parser;
use port_lookup::find_pids;
use processes::{KillOutcome, get_process_names, kill_pids};
use std::process::ExitCode;

// Third-party license notices, generated by cargo-about (see about.toml and about.hbs).
// Embedded so the notices ship with every release binary, as their licenses require
const CREDITS: &str = include_str!("../CREDITS.txt");

// Exit codes so portcull can be scripted (2 is left to clap for invalid arguments)
const EXIT_NOT_FOUND: u8 = 1;
const EXIT_CANCELLED: u8 = 3;
const EXIT_KILL_FAILED: u8 = 4;
const EXIT_LOOKUP_FAILED: u8 = 5;

fn main() -> ExitCode {
    let args = Args::parse();

    if args.licenses {
        print!("{}", CREDITS);
        return ExitCode::SUCCESS;
    }

    let proc_ids = match find_pids(&args) {
        Ok(proc_ids) => proc_ids,
        Err(err) => {
            eprintln!("Error: {}", err);
            return ExitCode::from(EXIT_LOOKUP_FAILED);
        }
    };

    if proc_ids.is_empty() {
        println!("No active processes found on provided ports; exiting.");

        // unprivileged lsof silently can't see sockets owned by other users
        #[cfg(any(target_os = "linux", target_os = "macos"))]
        eprintln!(
            "Hint: without root, lsof only sees your own processes. If you expected something here, try sudo."
        );

        return ExitCode::from(EXIT_NOT_FOUND);
    }

    let process_names = get_process_names(&proc_ids);

    if args.query {
        println!("Active processes found:");

        for (pid, name) in proc_ids.iter().zip(process_names.iter()) {
            println!("PID: {} | Name: {}", pid, name);
        }

        return ExitCode::SUCCESS;
    }

    match kill_pids(&proc_ids, &process_names, &args) {
        KillOutcome::Killed => ExitCode::SUCCESS,
        KillOutcome::Cancelled => ExitCode::from(EXIT_CANCELLED),
        KillOutcome::Failed => ExitCode::from(EXIT_KILL_FAILED),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn args_are_valid() {
        Args::command().debug_assert();
    }

    #[test]
    fn licenses_flag_needs_no_ports() {
        assert!(
            Args::try_parse_from(["portcull", "--licenses"])
                .unwrap()
                .licenses
        );
    }

    #[test]
    fn licenses_flag_is_exclusive() {
        assert!(Args::try_parse_from(["portcull", "--licenses", "3000"]).is_err());
    }

    #[test]
    fn ports_are_required_without_licenses_flag() {
        assert!(Args::try_parse_from(["portcull"]).is_err());
    }

    #[test]
    fn embedded_credits_cover_direct_dependencies() {
        assert!(CREDITS.contains("  - clap "));
        assert!(CREDITS.contains("  - sysinfo "));
    }
}
